### ISSUE TITLE
What Chrome plugins do you use?

### ISSUE THREAD

**Issue by kevinwolfcr** [kentcdodds/ama#468] opened 2018-08-21 02:43 UTC
Hi there Kent!

I've noticed on you [toolkits video](https://www.youtube.com/watch?v=ZWfY-v1DCTE) that you have some extra functionality on Chrome, as well as a different theming. What extensions/themes are you using?

**Comment by detrohutt** [comment] 2018-08-22 01:14
This is a duplicate of #409 so please see that issue for the answer.

**Closed by detrohutt** 2018-08-22 01:14 UTC
